[phases.build]
cmds = ["npm ci --ignore-scripts", "npm run db:generate -w packages/prisma", "npm run build -w packages/shared-types", "npm run build -w apps/api"]

[phases.start]
cmd = "npm run start -w apps/api"

[variables]
NODE_ENV = "production"
