services:
  - type: web
    name: social-platform-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate --schema=./packages/prisma/prisma/schema.prisma && npm run build -w packages/shared-types && npm run build -w apps/api
    startCommand: npm run start -w apps/api
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false